const json=(data,status=200,origin='*')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','access-control-allow-origin':origin,'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,OPTIONS'}});
const now=()=>Math.floor(Date.now()/1000), id=()=>crypto.randomUUID();
async function sha256(t){const b=new TextEncoder().encode(t),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hmac(t,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']);const h=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(t));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const enc=o=>btoa(JSON.stringify(o)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function session(p,s){const b=enc(p);return b+'.'+await hmac(b,s)}
async function verify(t,s){try{const [b,sg]=t.split('.');if(!b||!sg)return null;const e=await hmac(b,s);if(e!==sg)return null;const p=JSON.parse(atob(b.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-b.length%4)%4)));return p.exp<now()?null:p}catch{return null}}
async function auth(req,e){return verify(req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'',e.SESSION_SECRET)}
async function rp(path,e,opt={}){const r=await fetch('https://api.razorpay.com/v1/'+path,{method:opt.method||'GET',headers:{Authorization:'Basic '+btoa(`${e.RAZORPAY_KEY_ID}:${e.RAZORPAY_KEY_SECRET}`),'Content-Type':'application/json'},body:opt.body?JSON.stringify(opt.body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error?.description||'Razorpay error');return d}
export default{async fetch(req,e){const origin=e.FRONTEND_ORIGIN||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':origin,'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,OPTIONS'}});const u=new URL(req.url);try{
if(u.pathname==='/api/health')return json({ok:true},200,origin);
if(u.pathname==='/api/register'&&req.method==='POST'){const{x}=await req.json().catch(()=>({}));const{name,email,password}=x||{};if(!name||!email||!password||password.length<8)return json({error:'Name, email and 8+ character password required.'},400,origin);const em=email.trim().toLowerCase();if(await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(em).first())return json({error:'Email already registered.'},409,origin);const uid=id(),code='RUGC-'+uid.replaceAll('-','').slice(0,10).toUpperCase();await e.DB.prepare('INSERT INTO users(id,name,email,password_hash,referral_code,created_at) VALUES(?,?,?,?,?,?)').bind(uid,name.trim(),em,await sha256(password),code,now()).run();return json({token:await session({uid,exp:now()+2592000},e.SESSION_SECRET),user:{id:uid,name:name.trim(),email:em,referralCode:code}},201,origin)}
if(u.pathname==='/api/login'&&req.method==='POST'){const{name,email,password}=await req.json();const em=email?.trim().toLowerCase(),user=await e.DB.prepare('SELECT * FROM users WHERE email=?').bind(em).first();if(!user||user.password_hash!==await sha256(password||''))return json({error:'Invalid email or password.'},401,origin);return json({token:await session({uid:user.id,exp:now()+2592000},e.SESSION_SECRET),user:{id:user.id,name:user.name,email:user.email,referralCode:user.referral_code}},200,origin)}
if(u.pathname==='/api/me'&&req.method==='GET'){const s=await auth(req,e);if(!s)return json({error:'Unauthorized'},401,origin);const user=await e.DB.prepare('SELECT id,name,email,referral_code,created_at FROM users WHERE id=?').bind(s.uid).first();if(!user)return json({error:'User not found'},404,origin);const stats=await e.DB.prepare("SELECT COUNT(*) total,COALESCE(SUM(commission_gross),0) gross,COALESCE(SUM(tds_amount),0) tds,COALESCE(SUM(commission_net),0) net FROM referrals WHERE affiliate_user_id=? AND status='sale'").bind(s.uid).first();return json({user,stats},200,origin)}
if(u.pathname==='/api/course/order'&&req.method==='POST'){const s=await auth(req,e);if(!s)return json({error:'Login required.'},401,origin);const{referralCode}=await req.json().catch(()=>({}));let referralId=null;if(referralCode){const a=await e.DB.prepare('SELECT id FROM users WHERE referral_code=?').bind(referralCode).first();if(a&&a.id!==s.uid){referralId=id();await e.DB.prepare("INSERT INTO referrals(id,affiliate_user_id,referred_user_id,status,created_at,updated_at) VALUES(?,?,?,'pending',?,?)").bind(referralId,a.id,s.uid,now(),now()).run()}}const amount=Number(e.COURSE_AMOUNT_PAISE||294882),o=await rp('orders',e,{method:'POST',body:{amount,currency:'INR',receipt:'course_'+id().slice(0,12),notes:{user_id:s.uid,referral_id:referralId||''}}});await e.DB.prepare("INSERT INTO orders(id,razorpay_order_id,user_id,referral_id,amount,status,created_at) VALUES(?,?,?,?,?,'created',?)").bind(id(),o.id,s.uid,referralId,amount,now()).run();return json({orderId:o.id,amount,currency:'INR',keyId:e.RAZORPAY_KEY_ID},200,origin)}
if(u.pathname==='/api/payment/verify'&&req.method==='POST'){const s=await auth(req,e);if(!s)return json({error:'Unauthorized'},401,origin);const{razorpay_order_id,razorpay_payment_id,razorpay_signature}=await req.json(),o=await e.DB.prepare('SELECT * FROM orders WHERE razorpay_order_id=? AND user_id=?').bind(razorpay_order_id,s.uid).first();if(!o)return json({error:'Order not found'},404,origin);const ex=await hmac(`${o.razorpay_order_id}|${razorpay_payment_id}`,e.RAZORPAY_KEY_SECRET);if(ex!==razorpay_signature)return json({error:'Signature verification failed'},400,origin);await e.DB.prepare("UPDATE orders SET status='paid',razorpay_payment_id=?,paid_at=? WHERE id=?").bind(razorpay_payment_id,now(),o.id).run();return json({ok:true},200,origin)}
if(u.pathname==='/api/webhook'&&req.method==='POST'){const raw=await req.text(),sig=req.headers.get('X-Razorpay-Signature')||'';if(await hmac(raw,e.RAZORPAY_WEBHOOK_SECRET)!==sig)return new Response('Invalid signature',{status:400});const eid=req.headers.get('x-razorpay-event-id')||id();if(await e.DB.prepare('SELECT event_id FROM webhook_events WHERE event_id=?').bind(eid).first())return new Response('ok');const p=JSON.parse(raw);await e.DB.prepare('INSERT INTO webhook_events(event_id,event_name,created_at) VALUES(?,?,?)').bind(eid,p.event,now()).run();if(p.event==='order.paid'){const oe=p.payload?.order?.entity,pe=p.payload?.payment?.entity,o=await e.DB.prepare('SELECT * FROM orders WHERE razorpay_order_id=?').bind(oe?.id).first();if(o){await e.DB.prepare("UPDATE orders SET status='paid',razorpay_payment_id=?,paid_at=? WHERE id=?").bind(pe?.id||null,now(),o.id).run();if(o.referral_id){const gross=Math.round(o.amount*Number(e.COMMISSION_BPS||4000)/10000),tds=0,net=gross-tds;await e.DB.prepare("UPDATE referrals SET status='sale',order_id=?,sale_amount=?,commission_gross=?,tds_amount=?,commission_net=?,updated_at=? WHERE id=? AND status!='sale'").bind(o.razorpay_order_id,o.amount,gross,tds,net,now(),o.referral_id).run()}}}return new Response('ok')}
if(u.pathname==='/api/referrals'&&req.method==='GET'){const s=await auth(req,e);if(!s)return json({error:'Unauthorized'},401,origin);const r=await e.DB.prepare('SELECT id,status,sale_amount,commission_gross,tds_amount,commission_net,payout_status,created_at FROM referrals WHERE affiliate_user_id=? ORDER BY created_at DESC').bind(s.uid).all();return json({referrals:r.results},200,origin)}
return json({error:'Not found'},404,origin)}catch(err){console.error(err);return json({error:err.message||'Server error'},500,origin)}}};
